name: AQA Tests + Allure Report (GitHub Pages)

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 22 (Temurin)
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'

      - name: Verify Java version
        run: java -version

      - name: Run tests & generate Allure report
        run: |
          mvn clean test -Dsurefire.printSummary=true -Dsurefire.useFile=false -B -V
          mvn io.qameta.allure:allure-maven:report

      - name: Upload Allure HTML report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: target/site/allure-maven-plugin

      - name: Upload Surefire report
        uses: actions/upload-artifact@v4
        with:
          name: surefire-report
          path: target/surefire-reports

      - name: Upload Allure results (raw)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: target/allure-results

      - name: Upload Surefire reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: target/surefire-reports