name: API Tests + Allure Report (GitHub Pages)

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test-and-allure:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'

      - name: Run tests (generate allure-results)
        run: |
          mvn clean test \
            -Dallure.results.directory=target/allure-results \
            -B

      # ===== history (опционально, но правильно) =====
      - name: Download previous history
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: old-pages
        continue-on-error: true

      - name: Restore history
        run: |
          mkdir -p target/allure-results/history
          if [ -d "old-pages/history" ]; then
            cp -r old-pages/history/* target/allure-results/history/
          fi

      # ===== generate report =====
      - name: Generate Allure Report
        run: mvn io.qameta.allure:allure-maven:report

      - name: Prepare static site
        run: |
          mkdir -p public
          cp -r target/site/allure-maven-plugin/* public/

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    needs: test-and-allure
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    steps:
      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4